# Generated by Django 5.1.7 on 2025-03-25 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('supporting_evidence', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
